# Generated by Django 4.1.3 on 2022-12-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_hr_status_alter_manager_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='joining_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='joining_date',
            field=models.DateField(null=True),
        ),
    ]
