# Generated by Django 4.1.3 on 2022-12-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_hr_joining_date_alter_manager_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='alternate_contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='alternate_contact',
            field=models.IntegerField(null=True),
        ),
    ]
