# Generated by Django 4.1.3 on 2022-12-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_Id', models.CharField(max_length=12)),
                ('joining_date', models.DateField(null=True)),
                ('position', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('member_of', models.CharField(max_length=20)),
                ('guardian_name', models.CharField(max_length=20)),
                ('alternate_contact', models.IntegerField(null=True)),
                ('religion', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('Permanent_address', models.CharField(max_length=100)),
                ('current_address', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('previous_organisation', models.CharField(max_length=30)),
                ('previous_position', models.CharField(max_length=40)),
                ('previous_salary', models.CharField(max_length=10)),
                ('previous_joining_letter', models.CharField(max_length=100)),
                ('relieving_letter', models.ImageField(blank=True, null=True, upload_to='')),
                ('reason_of_relieving', models.CharField(max_length=200)),
            ],
        ),
    ]
