# Generated by Django 4.1.3 on 2022-12-01 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import management.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('contact', models.IntegerField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], max_length=8)),
                ('emp_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', management.manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_Id', models.CharField(max_length=12)),
                ('joining_date', models.DateField()),
                ('position', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], max_length=20)),
                ('member_of', models.CharField(max_length=20)),
                ('guardian_name', models.CharField(max_length=20)),
                ('alternate_contact', models.IntegerField()),
                ('religion', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('Permanent_address', models.CharField(max_length=100)),
                ('current_address', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('previous_organisation', models.CharField(max_length=30)),
                ('previous_position', models.CharField(max_length=40)),
                ('previous_salary', models.CharField(max_length=10)),
                ('previous_joining_letter', models.CharField(max_length=100)),
                ('relieving_letter', models.ImageField(blank=True, null=True, upload_to='')),
                ('reason_of_relieving', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employee',
                'db_table': 'Employee',
            },
            bases=('employee.user', models.Model),
            managers=[
                ('objects', management.manager.UserManager()),
            ],
        ),
    ]
