# Generated by Django 4.1.3 on 2022-12-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='alternate_contact',
            field=models.IntegerField(null=True),
        ),
    ]
