# Generated by Django 4.1.3 on 2022-12-02 07:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0003_rename_additional_details_additional_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Additional_Detail',
            new_name='AdditionalDetail',
        ),
    ]
