# Generated by Django 4.1.3 on 2022-12-02 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0004_rename_additional_detail_additionaldetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
